Formula/fsoc.rb

Automatically generated by [GoReleaser](https://goreleaser.com)

Updated fsoc to 0.46.2

---

README.md

Added entry for fsoc in readme

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.47.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.47.1

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.47.2

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.48.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.49.0

---

.github/PULL_REQUEST_TEMPLATE.md

Add a note that updating CODEOWNERS and README can happen through a separate PR.

Add note for automatic PRs to PULL_REQUEST_TEMPLATE.md

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.49.1

---

.github/settings.yml

Introduce branch protection via settings.yml

---

.github/settings.yml

@lelia @detiber please take a look.
For reference on why the settings look like this: https://github.com/cisco-open/homebrew-tap/pull/33#discussion_r1324559611

Update teams in settings.yml

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.50.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.51.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.51.1

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.53.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.54.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.56.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.57.2

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.58.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.58.1

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.59.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.61.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.62.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.62.1

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.63.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.64.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.66.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.67.0

---

Formula/fsoc.rb

Brew formula update for fsoc version v0.68.0
